### ISSUE TITLE
uninitialized constant Breadcrumbs (NameError)

### ISSUE THREAD

**Issue by jcope2013** [Rademade/rademade_admin#2]
ran rails s and got this stack trace:

```
/Users/JoshuaCope/Desktop/rademade_admin/lib/rademade_admin/breadcrumbs/render/rademade.rb:1:in `<top (required)>': uninitialized constant Breadcrumbs (NameError)
    from /Users/JoshuaCope/Desktop/rademade_admin/lib/rademade_admin/engine.rb:21:in `require'
    from /Users/JoshuaCope/Desktop/rademade_admin/lib/rademade_admin/engine.rb:21:in `block (2 levels) in <class:Engine>'
    from /Users/JoshuaCope/Desktop/rademade_admin/lib/rademade_admin/engine.rb:21:in `each'
    from /Users/JoshuaCope/Desktop/rademade_admin/lib/rademade_admin/engine.rb:21:in `block in <class:Engine>'
    from /Users/JoshuaCope/Desktop/rademade_admin/lib/rademade_admin/engine.rb:20:in `each'
    from /Users/JoshuaCope/Desktop/rademade_admin/lib/rademade_admin/engine.rb:20:in `<class:Engine>'
    from /Users/JoshuaCope/Desktop/rademade_admin/lib/rademade_admin/engine.rb:6:in `<module:RademadeAdmin>'
    from /Users/JoshuaCope/Desktop/rademade_admin/lib/rademade_admin/engine.rb:5:in `<top (required)>'
    from /Users/JoshuaCope/.rvm/gems/ruby-2.1.1@InboxHealth/gems/railties-4.1.5/lib/rails/engine/commands.rb:11:in `require'
    from /Users/JoshuaCope/.rvm/gems/ruby-2.1.1@InboxHealth/gems/railties-4.1.5/lib/rails/engine/commands.rb:11:in `<top (required)>'
    from bin/rails:12:in `require'
    from bin/rails:12:in `<main>'  
```

**Comment by Melanitski** [comment]
We found a core problem of this bug
jcope2013, may be it's not actual for you, but i wont to inform you about such fixes

Thank for you issue
